### PR TITLE
HasteResolver not resolving on Windows

### LINKED ISSUE #170: Aliases path errors
### Current Behavior
When I ran Haul on windows, in 91% it crashed and wrote errors: 

First three errors:

```
ERROR in ./~/haul/src/utils/polyfillEnvironment.js
Module not found: Error: Can't resolve 'InitializeCore' in 'C:\Users\Admin\Documents\Git-hub\snootik-app\node_modules\haul\src\utils'
 @ ./~/haul/src/utils/polyfillEnvironment.js 35:0-25
 @ multi ./~/haul/src/utils/polyfillEnvironment.js ./index.android.js

ERROR in ./~/react-native/Libraries/react-native/react-native-implementation.js
Module not found: Error: Can't resolve 'AccessibilityInfo' in 'C:\Users\Admin\Documents\Git-hub\snootik-app\node_modules\react-native\Libraries\react-native'
 @ ./~/react-native/Libraries/react-native/react-native-implementation.js 19:31-59
 @ ./src/index.js
 @ ./index.android.js
 @ multi ./~/haul/src/utils/polyfillEnvironment.js ./index.android.js

ERROR in ./~/react-native/Libraries/react-native/react-native-implementation.js
Module not found: Error: Can't resolve 'ActivityIndicator' in 'C:\Users\Admin\Documents\Git-hub\snootik-app\node_modules\react-native\Libraries\react-native'
 @ ./~/react-native/Libraries/react-native/react-native-implementation.js 20:31-59
 @ ./src/index.js
 @ ./index.android.js
 @ multi ./~/haul/src/utils/polyfillEnvironment.js ./index.android.js
```

### Haul Configuration (webpack.haul.js)
```
const path = require('path');

module.exports = ({ platform, root }, defaults) => ({
  entry: `./index.${platform}.js`,
  resolve: {
    ...defaults.resolve,
    alias: {
      ...defaults.resolve.alias,
      theme: path.join(root, 'src', 'styles'),
      ui: path.join(root, 'src', 'ui'),
      helpers: path.join(root, 'src', 'helpers'),
      config: path.join(root, 'src', 'config'),
    },
  },
});

```

### Your Environment
Windows 10
Visual Studio Code
Android emulator

| software         | version
| ---------------- | -------
| Haul      |  1.0.0-beta.0   
| react-native   |   0.45.0  
| node      |  6.10.0       
| npm or yarn     | 0.21.3

### PR DESCRIPTION
**Pull request by Krizzu**
Fixed a bug where we did not remove `package.json` from directories' path.

Fixes #170 and #175

### CODE REVIEW

File: src/utils/resolveModule.js [hunk 1]
```diff
@@ -15,4 +15,4 @@ const resolver = require('resolve');
 module.exports = (root: string, name: string) =>
   resolver
     .sync(`${name}/package.json`, { basedir: root })
-    .replace('/package.json', '');
+    .replace(/(\\|\\\\|\/)package.json$/, '');
```
Comment (satya164) [inline src/utils/resolveModule.js]: I'd prefer to use `path.dirname` instead of this

Comment (grabbou) [inline src/utils/resolveModule.js]: Lol yeah,

Comment (Krizzu) [inline src/utils/resolveModule.js]: okay, gonna push it in a minute
